### ISSUE TITLE
load_feature_sequence

### ISSUE THREAD

**Issue by anhanijr** [lmb-embrapa/machado#186]
Tried to load transcripts fasta (mRNA)
cmd line
python manage.py load_feature_sequence --file IWGSC_v1.1_HC_20170706_transcripts.fasta --organism 'Triticum aestivum' --soterm mRNA

error
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/m322745/dvlp/machado/machado_trigo/lib/python3.6/site-packages/Django-2.2-py3.6.egg/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/m322745/dvlp/machado/machado_trigo/lib/python3.6/site-packages/Django-2.2-py3.6.egg/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/m322745/dvlp/machado/machado_trigo/lib/python3.6/site-packages/Django-2.2-py3.6.egg/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/m322745/dvlp/machado/machado_trigo/lib/python3.6/site-packages/Django-2.2-py3.6.egg/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/m322745/dvlp/machado/machado_trigo/lib/python3.6/site-packages/machado-0.1.0-py3.6.egg/machado/management/commands/load_feature_sequence.py", line 61, in handle
    sequence_file = SequenceLoader(filename=filename, soterm=soterm)
TypeError: __init__() got an unexpected keyword argument 'soterm'

### Setup
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux

**Comment by azneto** [comment]
I've just fixed this problem. Please, pull the latest updates and try again.
